name: Build Firmware

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install PlatformIO
        run: pip install -U platformio

      - name: Cache PlatformIO directories
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio/packages
            ~/.platformio/platforms
            .pio/libdeps
          key: ${{ runner.os }}-platformio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-platformio-

      - name: Build Firmware for ESP32-s3-mini
        run: platformio run -e s3_mini

      - name: Prepare Artifacts
        run: |
          mkdir -p firmware
          cp .pio/build/esp32/firmware.bin firmware/OTGateway-s3-mini.bin
          ls -l firmware

      - name: Upload Firmware Artifacts (for Push events)
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: firmware-build
          path: firmware/

      - name: Upload Firmware to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: firmware/*
          tag: ${{ github.ref }}
          overwrite: true

          file_glob: true
